# This contains general information on the theme being used
[theme]
assets = "assets" # Static assets folder
rest = false # REST mode (disables all routes except path.hub.home and assets)

# Settings for Project Fluent translations
[fluent]
translation = "translation" # The folder containing Project Fluent tranlation files (.ftl)

# List of languages the theme provides with the order choosing the default
# (eg: en = ["en-us", "en-gb"], en will use "en-us" by default)
[fluent.languages]
en = ["en-us"] # Languages for English

# Template paths for the 'Hub' routes
[path.hub]
home = "hub/home" # The path to the index template
login = "hub/login" # The path to the login template
register = "hub/register" # The path to the register template

# StoryArchive has built-in support for SASS
[sass]
input = "index" # The main SASS file to be loaded
output = "cerberus" # The SASS output file name