# This contains general information on the theme being used
[theme]
assets = "assets" # Static assets folder
rest = false # REST mode (disables all routes except path.hub.home and assets)
translation = "translation" # The folder containing Project Fluent tranlation files

# Template paths for the 'Hub' routes
[path.hub]
home = "hub/home" # The path to the index template
login = "hub/login" # The path to the login template
register = "hub/register" # The path to the register template

# StoryArchive has built-in support for SASS
[sass]
inline = false # Inject the compiled SASS into all templates
input = "index" # The main SASS file to be loaded
output = "cerberus" # The SASS output file name